// Original integration test. Use generate_world_fixture.py; no private assets.
import fs from 'node:fs';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {createRegionBridge}=require('../web/terra_region.js');
const runtime=process.env.TERRA_WORLD_RUNTIME,fixture=process.env.TERRA_WLD_FIXTURE;
if(!runtime||!fixture)throw new Error('Set TERRA_WORLD_RUNTIME and TERRA_WLD_FIXTURE');
const factory=require(runtime),bridge=createRegionBridge(()=>factory({wasmBinary:fs.readFileSync(runtime.replace(/\.js$/,'.wasm'))}));
const world=new Uint8Array(fs.readFileSync(fixture)), original=world.slice();
const records=await bridge.read(world,1,2,2,3);assert.equal(records.length,192);
const view=new DataView(records.buffer);view.setUint32(16,1|(4<<24),true);view.setUint32(20,(128|(1<<8)|(2<<16)|(15<<24))>>>0,true);
const request=JSON.stringify({x:2,y:4,width:2,height:3,recordCount:6,recordSourceId:2,mode:'overlay'});
const candidate=await bridge.operation(world,'stamp_tiles',request,records,new Uint8Array());
assert.deepEqual(await bridge.read(candidate,2,4,2,3),records);
const maps=new Uint8Array(24);maps[10]=3;maps[16]=1;maps[22]=1;
assert.ok((await bridge.pixel(world,2,3,2,2,maps,new Uint16Array([1,0,0,1]))).length);
await assert.rejects(()=>bridge.operation(world,'stamp_tiles',request,records.slice(0,32),new Uint8Array()));
assert.deepEqual(world,original);assert.equal((await bridge.read(world,1,2,2,3)).length,192);
console.log('PASS: WASM all-layer region roundtrip, stamp, indexed pixel, reject/recovery, immutable input');
const dirtMaps=maps.slice();dirtMaps[16]=0;
const dirtWorld=await bridge.pixel(candidate,2,4,1,1,dirtMaps,new Uint16Array([1]));
const dirtCell=new DataView((await bridge.read(dirtWorld,2,4,1,1)).buffer);
assert.equal(dirtCell.getUint32(8,true)&0xffff,0);assert.equal((dirtCell.getUint32(8,true)>>>16)&1,1);
assert.equal(dirtCell.getUint32(16,true),view.getUint32(16,true));assert.equal(dirtCell.getUint32(20,true),view.getUint32(20,true));
const wallMaps=maps.slice();wallMaps[22]=2;wallMaps[18]=2;
const wallWorld=await bridge.pixel(candidate,2,4,1,1,wallMaps,new Uint16Array([1])),wallCell=new DataView((await bridge.read(wallWorld,2,4,1,1)).buffer);
assert.equal(wallCell.getUint32(8,true),view.getUint32(8,true));assert.equal(wallCell.getUint32(20,true),view.getUint32(20,true));assert.equal(wallCell.getUint32(16,true)&65535,2);
const clearMaps=maps.slice();clearMaps[22]=0;
const clearWorld=await bridge.pixel(candidate,2,4,1,1,clearMaps,new Uint16Array([1])),clearCell=new DataView((await bridge.read(clearWorld,2,4,1,1)).buffer);
assert.equal((clearCell.getUint32(8,true)>>>16)&1,0);assert.equal(clearCell.getUint32(16,true),view.getUint32(16,true));assert.equal(clearCell.getUint32(20,true),view.getUint32(20,true));
console.log('PASS: safe pixel merge dirt0, foreground/wall-only/erase semantics preserve unrelated layers');
const cleared=records.slice();const cv=new DataView(cleared.buffer);cv.setUint32(8,0,true);cv.setUint32(16,0,true);cv.setUint32(20,0,true);
const replaced=await bridge.replace(candidate,2,4,2,3,cleared),replacedRead=await bridge.read(replaced,2,4,2,3),rv=new DataView(replacedRead.buffer);assert.equal(rv.getUint32(8,true),0);assert.equal(rv.getUint32(16,true),0);assert.equal(rv.getUint32(20,true),0);
if(process.env.TERRA_OBJECT_FIXTURE){
 const source=new Uint8Array(fs.readFileSync(process.env.TERRA_OBJECT_FIXTURE)),r=await bridge.read(source,1,2,8,3),o=await bridge.objects(source,1,2,8,3);
 const request=JSON.stringify({x:1,y:10,width:8,height:3,recordCount:24,recordSourceId:2,objectSourceId:3,objectCount:3,objectBytes:o.length,mode:'overlay'});
 const pasted=await bridge.operation(source,'stamp_tiles',request,r,o),companion=await bridge.objects(pasted,1,10,8,3);assert.deepEqual(companion.slice(32),o.slice(32));
 const paint=r.slice(),d=new DataView(paint.buffer);d.setUint32(16,d.getUint32(16,true)|(3<<16),true);d.setUint32(20,15<<24,true);
 const edited=await bridge.replace(source,1,2,8,3,paint);assert.deepEqual(await bridge.objects(edited,1,2,8,3),o);
 await assert.rejects(()=>bridge.objects(source,2,2,1,2));d.setUint32(8,0,true);await assert.rejects(()=>bridge.replace(source,1,2,8,3,paint));
 await assert.rejects(()=>bridge.pixel(source,1,2,2,2,maps,new Uint16Array([1,0,0,1])));
 console.log('PASS: WASM chest inventory, sign text, tile entity paste/preservation and structural/partial rejection');
}
const candidates=new Uint32Array([0xff0000,0xff0000,0x0000ff]),candidateFlags=new Uint32Array([0,3,2]),queries=new Uint32Array([0xfe0000,0x0000fe]);
assert.deepEqual(await bridge.match(queries,candidates,candidateFlags,0),new Uint32Array([0,2]));
assert.deepEqual(await bridge.match(queries,candidates,candidateFlags,2|16),new Uint32Array([1,1]));
assert.deepEqual(await bridge.match(queries,new Uint32Array([0]),new Uint32Array([0]),2),new Uint32Array([0xffffffff,0xffffffff]));
await assert.rejects(()=>bridge.match(queries,candidates,candidateFlags,2|8));
console.log('PASS: authoritative RGB candidate matching, painted/wall filters, missing sentinel, contradictory filter rejection');
