// Real packaged WASM and browser worker bootstrap in Node worker_threads.
// Public synthetic fixtures only; owner lifetime is measured, not browser RSS.
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {createClient} = require('../../web/terra_worker_rpc.js');
const {workerFactory} = require('./helpers/engine_worker_host.cjs');
const root = path.resolve(__dirname, '../..');
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const fixture = new Uint8Array(fs.readFileSync(path.join(root, 'assets/qa/synthetic-objects.wld')));
const originalHash = hash(fixture);
const factory = workerFactory({root});
const client = createClient('document', {...factory, timeoutMs:10000});
const owners = () => ({created:factory.threads.length,
  active:factory.threads.filter(thread => thread.threadId !== -1).length,
  exited:factory.threads.filter(thread => thread.threadId === -1).length});
const report = {
  schema:'abc.document-worker-retirement.v1', status:'running', cycles:[], failedHandoffs:[],
  fixture:{path:'assets/qa/synthetic-objects.wld', bytes:fixture.length, sha256:originalHash, provenance:'original-synthetic'},
  playerProvenance:'schema-generated by createPlayer',
  runtime:{node:process.versions.node, v8:process.versions.v8, platform:process.platform, arch:process.arch},
  measurement:'Actual Node worker creation/exit; process RSS is contextual only, not browser memory or a leak verdict',
  caveats:['Node terminate is asynchronous; each retirement awaits the real thread exit.',
    'Native allocation and individual worker Wasm heap counters are not exposed by this protocol.',
    'Tiny public synthetic fixtures do not establish large-world browser memory behavior.'],
};
function snapshot() {
  const {rss, heapUsed, external, arrayBuffers} = process.memoryUsage();
  return {...owners(), nodeProcessRssBytes:rss, mainThreadHeapUsedBytes:heapUsed,
    mainThreadExternalBytes:external, mainThreadArrayBufferBytes:arrayBuffers};
}
async function awaitExit(index) {
  let timer;
  try {
    await Promise.race([factory.exits[index], new Promise((_, reject) => {
      timer = setTimeout(() => reject(new Error('Retired document worker did not exit')), 10000);
    })]);
  } finally { clearTimeout(timer); }
  assert.equal(factory.threads[index].threadId, -1, 'Retirement must complete at the actual thread boundary');
  assert.equal(owners().active, 0, 'No live document worker remains after final close and exit');
}
async function closeLast(handle, index, row, field) {
  const before = snapshot(); assert.equal(before.active, 1);
  await client.close(handle);
  const afterAck = snapshot();
  await awaitExit(index);
  row[field] = {beforeClose:before, afterCloseAck:afterAck, afterThreadExit:snapshot()};
}

(async () => {
  let world = fixture, player = null, lastPublicHandle = 0;
  report.before = snapshot();
  try {
    for (let cycle = 0; cycle < 8; cycle++) {
      const row = {cycle, before:snapshot()}; report.cycles.push(row);
      assert.equal(row.before.active, 0);
      const worldInputHash = hash(world), playerInputHash = player && hash(player);
      const wld = JSON.parse(await client.open(world, 'wld'));
      const ownerIndex = factory.threads.length - 1;
      assert.ok(wld.handle > lastPublicHandle);
      const plr = JSON.parse(player ? await client.open(player, 'plr') : await client.createPlayer('Retirement synthetic'));
      assert.equal(factory.threads.length, ownerIndex + 1, 'WLD and PLR must share one live owner');
      assert.equal(owners().active, 1);
      const expectedTime = cycle + 0.25, expectedName = 'Retirement cycle ' + cycle, expectedLife = 90 + cycle;
      await client.mutate(wld.handle, 'header_patch', JSON.stringify({patch:{worldName:expectedName, time:expectedTime}}));
      await client.mutate(plr.handle, 'player_patch', JSON.stringify({patch:{statLife:expectedLife}}));
      const savedWorld = await client.save(wld.handle), savedPlayer = await client.save(plr.handle);
      const playerMetadata = JSON.parse(await client.inspect(plr.handle));
      const projected = await client.projectPlayer(JSON.stringify(playerMetadata));
      assert.ok(projected.length > 0); assert.equal(owners().active, 1, 'Projection must preserve shared documents');
      assert.equal(hash(world), worldInputHash); if (player) assert.equal(hash(player), playerInputHash);
      row.loaded = snapshot();
      row.outputs = {worldBytes:savedWorld.length, worldSha256:hash(savedWorld), playerBytes:savedPlayer.length, playerSha256:hash(savedPlayer), projectedBytes:projected.length};
      await client.close(wld.handle); assert.equal(owners().active, 1, 'Closing WLD cannot terminate its shared PLR');
      assert.equal(JSON.parse(await client.inspect(plr.handle)).statLife, expectedLife);
      await closeLast(plr.handle, ownerIndex, row, 'firstRetirement');

      // Both saved byte buffers must remain readable after their owner exits.
      const reopenedWorld = JSON.parse(await client.open(savedWorld, 'wld'));
      const reopenedOwner = factory.threads.length - 1;
      assert.equal(reopenedOwner, ownerIndex + 1, 'Reopen must use a new actual worker');
      const reopenedPlayer = JSON.parse(await client.open(savedPlayer, 'plr'));
      assert.equal(reopenedWorld.metadata.header.worldName, expectedName);
      assert.equal(reopenedWorld.metadata.header.time, expectedTime);
      assert.equal(reopenedPlayer.metadata.statLife, expectedLife);
      assert.equal(hash(await client.save(reopenedWorld.handle)), row.outputs.worldSha256);
      assert.equal(hash(await client.save(reopenedPlayer.handle)), row.outputs.playerSha256);
      await client.close(reopenedPlayer.handle); assert.equal(owners().active, 1, 'Closing PLR cannot terminate its shared WLD');
      assert.equal(JSON.parse(await client.inspect(reopenedWorld.handle)).header.time, expectedTime);
      await closeLast(reopenedWorld.handle, reopenedOwner, row, 'reopenedRetirement');
      await assert.rejects(client.inspect(wld.handle), {code:'STALE_HANDLE'});
      await client.close(plr.handle); assert.equal(owners().created, reopenedOwner + 1, 'Stale cleanup cannot create a worker');
      lastPublicHandle = reopenedPlayer.handle;
      world = savedWorld; player = savedPlayer;
      row.after = snapshot();
    }
    assert.equal(hash(fixture), originalHash);
    assert.equal(hash(fs.readFileSync(path.join(root, 'assets/qa/synthetic-objects.wld'))), originalHash);
    assert.deepEqual(owners(), {created:16, active:0, exited:16});
    for (const method of ['open','createPlayer']) {
      const row = {method, before:snapshot()}; report.failedHandoffs.push(row);
      const prior = JSON.parse(await client.open(fixture, 'wld')), ownerIndex = factory.threads.length - 1;
      await client.close(prior.handle);
      // This immediate request cancels the preceding close's idle check. Its
      // rejected response must schedule a replacement check for the empty owner.
      await assert.rejects(method === 'open' ? client.open(new Uint8Array([1]), 'wld') : client.createPlayer(''), error => {
        assert.equal(error.code, 'WORKER_ENGINE'); row.error = error.message; return true;
      });
      await awaitExit(ownerIndex); row.afterFailedOwnerExit = snapshot();
      const recovered = JSON.parse(await client.open(fixture, 'wld')), recoveredOwner = factory.threads.length - 1;
      assert.equal(recoveredOwner, ownerIndex + 1);
      assert.equal(hash(await client.save(recovered.handle)), originalHash);
      await closeLast(recovered.handle, recoveredOwner, row, 'recoveredRetirement');
    }
    assert.deepEqual(owners(), {created:20, active:0, exited:20});
    report.status = 'passed';
  } catch (error) {
    report.status = 'failed'; report.error = String(error.stack || error); throw error;
  } finally {
    await client.dispose(); await Promise.all(factory.exits);
    report.after = snapshot();
    report.artifacts = ['web/terra_worker_rpc.js','web/terra_engine.js','web/terra_engine_worker.js','web/engine/world.js','web/engine/world.wasm','web/engine/player.js','web/engine/player.wasm'].map(file => {
      const bytes = fs.readFileSync(path.join(root, file)); return {path:file, bytes:bytes.length, sha256:hash(bytes)};
    });
    if (process.env.TERRA_DOCUMENT_RETIRE_REPORT) {
      fs.mkdirSync(path.dirname(process.env.TERRA_DOCUMENT_RETIRE_REPORT), {recursive:true});
      fs.writeFileSync(process.env.TERRA_DOCUMENT_RETIRE_REPORT, JSON.stringify(report, null, 2) + '\n');
    }
  }
  console.log('PASS: 8 real-WASM shared WLD/PLR cycles plus failed open/create handoff recovery; 20 workers created and exited; 0 live owners; source/output integrity verified');
})().catch(error => { console.error(error); process.exitCode = 1; });
